package backend.options;

import backend.options.*;

class Options {
    //Options are generated by the macro which gets data from the json file, this class WILL be used I'm sure but for now its mostly generated by the macro
}
